language: go
go:
- '1.10'

sudo: required

services:
  - docker

install:
- echo "install"
# - go get -u "github.com/astaxie/beego"
# - go get -u "github.com/bitly/go-simplejson"
# - go get -u "github.com/go-sql-driver/mysql"
- pwd
# - cd ~/server/server
# - go build main.go
# - ls

script:
- echo "script"
- pwd
- go version
- cd docker
- docker build -t goseverimage $PWD

#

before_install:
- openssl aes-256-cbc -K $encrypted_bae4eee6b0f8_key -iv $encrypted_bae4eee6b0f8_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d

after_success:
- chmod 600 ~/.ssh/id_rsa   #还是Linux文件权限问题
- ssh travis@139.199.166.124 -o StrictHostKeyChecking=no "cd /home/travis/server && chmod +x ./docker/deploy.sh && ./docker/deploy.sh"

addons:
  ssh_known_hosts: 139.199.166.124
